[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

max_frequency = "1m0s"
