[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email.template]
# leave empty or add templates later
